/* The C half of the macOS watcher.

FSEvents needs a C callback, and cgo needs that callback to reach Go through a
plain integer rather than a Go pointer — the stream outlives the call that
creates it and is entered from a thread the Go runtime did not make, so a Go
pointer handed to it would be both retained by C and moved by the collector.
What lives here is therefore the stream's construction, the trampoline that
turns a callback into a call, and the accessors that let Go read what FSEvents
passed without overlaying a struct on it.

This is a header rather than a .c file because fsmonitor_watch_darwin.go uses
//export: cgo copies such a file's preamble into more than one translation unit,
and while a definition there would be a duplicate symbol, a static function in a
header is not. Everything here is static or static inline for that reason, and
nothing here is a declaration of something defined in another translation unit
except qinFseventsDispatch, which cgo generates. */

#include <CoreServices/CoreServices.h>
#include <dispatch/dispatch.h>
#include <stddef.h>
#include <stdint.h>

/* qinFseventsDispatch is generated by cgo from the //export of that name. It is
declared here because one of the translation units the preamble is copied into
never sees _cgo_export.h, and calling an undeclared function is an error in C99
rather than a warning. The signature must match the generated one exactly:
void * for both arrays, not const uint32_t *, or the two declarations conflict
in the unit that does see the generated header. */
extern void qinFseventsDispatch(uintptr_t handle, void *paths, size_t numEvents, void *flags);

/* The stream asks for per-path events, for no deferral, and to be told when the
watched root itself is gone. It is built from the SDK's own macros rather than
from numbers copied into Go, so there is nothing here to get wrong. */
#define QIN_FSEVENTS_CREATE_FLAGS                                                         \
	(kFSEventStreamCreateFlagFileEvents | kFSEventStreamCreateFlagNoDefer |           \
	 kFSEventStreamCreateFlagWatchRoot)

/* qin_fsevents_abi_check compares the flag values the Go side transcribed
against the SDK's, which is the check that makes the transcription safe: without
it, a wrong value would make events decode into decisions nobody intended, and
nothing outside would show it — a watcher that reports nothing looks exactly
like a tree that never changes.

The order of the table must match fsEventFlags in fsmonitor_fsevents.go. A
mismatch there can only report a false error, never a false pass, and a false
error means the event backend is refused and status scans everything — which is
correct, just slower. */
static inline const char *qin_fsevents_abi_check(const unsigned int *ours, size_t n) {
	static const struct {
		const char *name;
		unsigned int value;
	} table[] = {
	    {"MustScanSubDirs", kFSEventStreamEventFlagMustScanSubDirs},
	    {"UserDropped", kFSEventStreamEventFlagUserDropped},
	    {"KernelDropped", kFSEventStreamEventFlagKernelDropped},
	    {"EventIdsWrapped", kFSEventStreamEventFlagEventIdsWrapped},
	    {"HistoryDone", kFSEventStreamEventFlagHistoryDone},
	    {"RootChanged", kFSEventStreamEventFlagRootChanged},
	    {"Mount", kFSEventStreamEventFlagMount},
	    {"Unmount", kFSEventStreamEventFlagUnmount},
	    {"ItemCreated", kFSEventStreamEventFlagItemCreated},
	    {"ItemRemoved", kFSEventStreamEventFlagItemRemoved},
	    {"ItemInodeMetaMod", kFSEventStreamEventFlagItemInodeMetaMod},
	    {"ItemRenamed", kFSEventStreamEventFlagItemRenamed},
	    {"ItemModified", kFSEventStreamEventFlagItemModified},
	    {"ItemFinderInfoMod", kFSEventStreamEventFlagItemFinderInfoMod},
	    {"ItemChangeOwner", kFSEventStreamEventFlagItemChangeOwner},
	    {"ItemXattrMod", kFSEventStreamEventFlagItemXattrMod},
	    {"ItemIsDir", kFSEventStreamEventFlagItemIsDir},
	};
	const size_t rows = sizeof(table) / sizeof(table[0]);
	if (n != rows) {
		return "the check table and the Go constants are different lengths";
	}
	for (size_t i = 0; i < rows; i++) {
		if (ours[i] != table[i].value) {
			return table[i].name;
		}
	}
	return NULL;
}

/* qin_fsevents_noop is what qin_fsevents_drain_queue synchronizes on. */
static inline void qin_fsevents_noop(void *context) { (void)context; }

/* qin_fsevents_trampoline is the callback the stream is created with. It does
nothing but hand the batch to Go: the handle is the integer Go filed the watcher
under, and eventPaths is an array of C strings because the stream is not created
with kFSEventStreamCreateFlagUseCFTypes. */
static inline void qin_fsevents_trampoline(ConstFSEventStreamRef stream,
                                           void *info,
                                           size_t numEvents,
                                           void *eventPaths,
                                           const FSEventStreamEventFlags eventFlags[],
                                           const FSEventStreamEventId eventIds[]) {
	(void)stream;
	(void)eventIds;
	qinFseventsDispatch((uintptr_t)info, eventPaths, numEvents, (void *)eventFlags);
}

/* qin_fsevents_create builds the stream, rooted at one resolved path.

sinceWhen is the present: the stream reports what happens from here on and
nothing that happened before, which is what lets the daemon write READY and mean
"coverage is complete from this point". The latency is a coalescing window, not
a delay, because NoDefer is set. */
static inline FSEventStreamRef qin_fsevents_create(const char *root, uintptr_t handle, double latency) {
	CFStringRef path = CFStringCreateWithCString(kCFAllocatorDefault, root, kCFStringEncodingUTF8);
	if (path == NULL) {
		return NULL;
	}
	const void *values[1];
	values[0] = path;
	CFArrayRef paths = CFArrayCreate(kCFAllocatorDefault, values, 1, &kCFTypeArrayCallBacks);
	CFRelease(path);
	if (paths == NULL) {
		return NULL;
	}
	FSEventStreamContext context = {0, (void *)handle, NULL, NULL, NULL};
	FSEventStreamRef stream = FSEventStreamCreate(kCFAllocatorDefault,
	                                              qin_fsevents_trampoline,
	                                              &context,
	                                              paths,
	                                              kFSEventStreamEventIdSinceNow,
	                                              (CFTimeInterval)latency,
	                                              QIN_FSEVENTS_CREATE_FLAGS);
	CFRelease(paths);
	return stream;
}

/* qin_fsevents_path and qin_fsevents_flag read the arrays FSEvents passes.
Indexing them in Go would mean pointer arithmetic on unsafe.Pointer, which is
exactly the kind of thing that is wrong in a way the tests cannot see. */
static inline const char *qin_fsevents_path(const void *paths, size_t i) {
	return ((const char *const *)paths)[i];
}

static inline unsigned int qin_fsevents_flag(const void *flags, size_t i) {
	return ((const unsigned int *)flags)[i];
}

/* qin_fsevents_drain_queue waits for a callback that is already running to
finish. FSEventStreamInvalidate stops new ones from starting, but the stream's
own machinery may still be inside the last one when the stream is released, and
releasing it out from under that is a crash in code with no Go frames to explain
it. A synchronous no-op on the stream's own serial queue is ordered after
whatever is running and before anything released afterwards. */
static inline void qin_fsevents_drain_queue(dispatch_queue_t queue) {
	dispatch_sync_f(queue, NULL, qin_fsevents_noop);
}

/* qin_fsevents_release_queue drops the queue this file created. Under
OS_OBJECT_USE_OBJC — which is what the SDK's dispatch headers select unless the
compiler is in ARC mode — dispatch objects are Objective-C objects and the
manual release functions do not exist; cgo compiles this as plain C, so the
macro is 0 and the release is the right call, but the guard is what keeps the
file compiling if that ever changes. */
static inline void qin_fsevents_release_queue(dispatch_queue_t queue) {
#if !OS_OBJECT_USE_OBJC
	dispatch_release(queue);
#endif
}
